[project]
name = "stai"
version = "0.1.0"
description = "💻 Silicon-Transcription AI: Get the transcription of an audio file on your Apple Silicon Chip."
readme = "README.md"
authors = [
    { name = "chainyo", email = "thomas@chainyo.dev" }
]
requires-python = ">=3.12"
dependencies = [
    "ane-transformers>=0.1.1",
    "coremltools>=8.1",
    "openai-whisper>=20240930",
    "typer>=0.15.1",
    "yt-dlp>=2024.12.23",
]

[project.scripts]
stai = "stai:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
